groupDefs:
  CEU2: CEU.SG,-<NA12889.SG>,-<NA12890.SG>
  FIN2: FIN.SG,-<HG00383.SG>,-<HG00384.SG>
  GBR2: GBR.SG,-<HG01791.SG>,-<HG02215.SG>
  IBS2: IBS.SG,-<HG02238.SG>,-<HG02239.SG>
  TSI2: TSI.SG,-<NA20828.SG>,-<NA20832.SG>
  YRI2: YRI.SG,-<NA19257.SG>
popLefts:
- <I0156.SG>
- <I0157.SG>
- <I0159.SG>
- <I0160.SG>
- <I0161.SG>
- <NA12889.SG>
- <NA12890.SG>
- <HG00383.SG>
- <HG00384.SG>
- <HG01791.SG>
- <HG02215.SG>
- <HG02238.SG>
- <HG02239.SG>
- <NA20828.SG>
- <NA20832.SG>
popRights:
- CEU2
- FIN2
- GBR2
- IBS2
- TSI2
- CHS.SG
- JPT.SG
- PEL.SG
- YRI2
outgroup: <NA19257.SG>
