name: jupyter
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - conda-forge::jupyter=1.0.0
  - conda-forge::papermill=2.1.2
  - conda-forge::python=3.8.5
  - conda-forge::numpy=1.19.1
  - conda-forge::matplotlib=3.3.0
  - conda-forge::scikit-bio=0.5.6
  - conda-forge::scikit-learn=0.23.2
  - conda-forge::msprime=0.7.4
  - conda-forge::tskit=0.2.3
  - conda-forge::pandas=1.1.2
  - pip
  - pip:
    - wcmatch
