groupDefs:
  Basque2: Basque.SDG,-<HGDP01357.SDG>,-<HGDP01358.SDG>
  BergamoItalian2: Italian_North.SDG,-<HGDP01149.SDG>,-<HGDP01151.SDG>,-<HGDP01161.SDG>,-<HGDP01162.SDG>
  French2: French.SDG,-<HGDP00511.SDG>,-<HGDP00512.SDG>
  Han2: Han.SDG,-<HGDP00774.SDG>,-<HGDP00775.SDG>
  Karitiana2: Karitiana.SDG,-<HGDP00995.SDG>,-<HGDP00998.SDG>
  Mbuti2: Mbuti.SDG,-<HGDP00449.SDG>,-<HGDP00450.SDG>
  Orcadian2: Orcadian.SDG,-<HGDP00794.SDG>,-<HGDP00795.SDG>
  Russian2: Russian.SDG,-<HGDP00879.SDG>,-<HGDP00880.SDG>
  Sardinian2: Sardinian.SDG,-<HGDP00665.SDG>,-<HGDP00666.SDG>
popLefts:
- <I0156.SG>
- <I0157.SG>
- <I0159.SG>
- <I0160.SG>
- <I0161.SG>
- <I0769.SG>
- <I0773.SG>
- <I0774.SG>
- <I0777.SG>
- <I0789.SG>
- <3DT16.SG>
- <3DT26.SG>
- <6DT18.SG>
- <6DT21.SG>
- <6DT22.SG>
- <6DT23.SG>
- <6DT3.SG>
- <M1489.SG>
- <NO3423.SG>
- <HGDP01357.SDG>
- <HGDP01358.SDG>
- <HGDP01149.SDG>
- <HGDP01151.SDG>
- <HGDP00511.SDG>
- <HGDP00512.SDG>
- <HGDP00774.SDG>
- <HGDP00775.SDG>
- <HGDP00995.SDG>
- <HGDP00998.SDG>
- <HGDP00449.SDG>
- <HGDP00450.SDG>
- <HGDP00794.SDG>
- <HGDP00795.SDG>
- <HGDP00879.SDG>
- <HGDP00880.SDG>
- <HGDP00665.SDG>
- <HGDP00666.SDG>
- <HGDP01161.SDG>
- <HGDP01162.SDG>
popRights:
- Basque2
- BergamoItalian2
- French2
- Han2
- Karitiana2
- Mbuti2
- Orcadian2
- Russian2
- Sardinian2
outgroup: <HGDP00987.SDG>